@ApiInvoice_HostAddress = http://localhost:5009
@invoice_id = 714a9cd6-f81a-4d94-aca4-01ba28b7b4f0
@page = 1
@pageSize = 100
### Listar notas fiscais
GET {{ApiInvoice_HostAddress}}/api/invoices?page={{page}}&pageSize={{pageSize}}
Accept: application/json

### Buscar nota fiscal por id
GET {{ApiInvoice_HostAddress}}/api/invoices/{{invoice_id}}
Accept: application/json

### Criar nota fiscal
POST {{ApiInvoice_HostAddress}}/api/invoices
Content-Type: application/json


### Atualizar nota fiscal
PUT {{ApiInvoice_HostAddress}}/api/invoices/{{invoice_id}}
Content-Type: application/json

{
  "status": 2
}

### Excluir nota fiscal
DELETE {{ApiInvoice_HostAddress}}/api/invoices/{{invoice_id}}