services:

  postgres-produtos:
    image: postgres:16
    container_name: db_produtos
    environment:
      POSTGRES_USER: produtos
      POSTGRES_PASSWORD: produtos
      POSTGRES_DB: produtos
    ports:
      - "5433:5432"
    volumes:
      - postgres_produtos_data:/var/lib/postgresql/data

  postgres-nota_fiscal:
    image: postgres:16
    container_name: db_nota_fiscal
    environment:
      POSTGRES_USER: nota_fiscal
      POSTGRES_PASSWORD: nota_fiscal
      POSTGRES_DB: nota_fiscal
    ports:
      - "5434:5432"
    volumes:
      - postgres_nota_fiscal_data:/var/lib/postgresql/data

volumes:
  postgres_produtos_data:
  postgres_nota_fiscal_data: