@ApiInvoice_HostAddress = http://localhost:5009
@invoice_id = 2d7d9213-d3ea-4ab5-90b4-22e7de26dee2
@product_id = 9716b6ae-f6bc-4ef1-82de-83dff34e14a7
@page = 1
@pageSize = 100
### Health check
GET {{ApiInvoice_HostAddress}}/health

### Listar notas fiscais
GET {{ApiInvoice_HostAddress}}/api/invoices?page={{page}}&pageSize={{pageSize}}
Accept: application/json

### Buscar nota fiscal por id
GET {{ApiInvoice_HostAddress}}/api/invoices/{{invoice_id}}
Accept: application/json

### Criar nota fiscal
POST {{ApiInvoice_HostAddress}}/api/invoices
Content-Type: application/json

{
  "customerName": "Cliente Teste",
  "customerDocument": "12345678901"
}

### Fechar nota fiscal
PUT {{ApiInvoice_HostAddress}}/api/invoices/{{invoice_id}}/close

### Excluir nota fiscal
DELETE {{ApiInvoice_HostAddress}}/api/invoices/{{invoice_id}}