@ApiInvoice_HostAddress = http://localhost:5009
@invoice_id = 24032926-6aab-4508-9874-3736316a545b
@page = 1
@pageSize = 100
### Health check
GET {{ApiInvoice_HostAddress}}/health

### Listar notas fiscais
GET {{ApiInvoice_HostAddress}}/api/invoices?page={{page}}&pageSize={{pageSize}}
Accept: application/json

### Buscar nota fiscal por id
GET {{ApiInvoice_HostAddress}}/api/invoices/{{invoice_id}}
Accept: application/json

### Criar nota fiscal
POST {{ApiInvoice_HostAddress}}/api/invoices
Content-Type: application/json

{
  "customerName": "Cliente Teste",
  "customerDocument": "12345678901"
}

### Adicionar produtos na nota fiscal
PUT {{ApiInvoice_HostAddress}}/api/invoices/{{invoice_id}}/items
Content-Type: application/json

{
  "products": [
    {
      "productId": "9716b6ae-f6bc-4ef1-82de-83dff34e14a7",
      "quantity": 2
    },
    {
      "productId": "11bd7bcf-000d-4088-b4d6-18bacbc76f53",
      "quantity": 1
    }
  ]
}

### Excluir nota fiscal
DELETE {{ApiInvoice_HostAddress}}/api/invoices/{{invoice_id}}