@ApiProduto_HostAddress = http://localhost:5242
@productId = deb0f505-e694-4c56-91e7-4ad1e0c8644f
@page = 1
@pageSize = 10
### Listar produtos ativos (paginado)
GET {{ApiProduto_HostAddress}}/api/products?page={{page}}&pageSize={{pageSize}}
Accept: application/json

###

### Criar produto
POST {{ApiProduto_HostAddress}}/api/products
Content-Type: application/json

{
  "code": "PRO-001",
  "name": "Produto Teste",
  "stock": 10,
  "price": 199.99
}

###

### Buscar produto por id
GET {{ApiProduto_HostAddress}}/api/products/{{productId}}
Accept: application/json

###

### Buscar produtos por lote de ids
POST {{ApiProduto_HostAddress}}/api/products/batch
Content-Type: application/json

{
  "ids": [
    "{{productId}}",
    "58e3fd41-a0f6-475d-8c93-dedd8f228f9e"
  ]
}

###

### Atualizar produto
PUT {{ApiProduto_HostAddress}}/api/products/{{productId}}
Content-Type: application/json

{
  "code": "PRD-001",
  "name": "Produto Teste Atualizado",
  "stock": 29,
  "price": 249.99
}

###

### Deletar (soft delete)
DELETE {{ApiProduto_HostAddress}}/api/products/{{productId}}
Accept: application/json